# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "0 0 */14 * *"
    displayName: "Bi-monthly build"
    branches:
      include:
        - master
        - benchmarking

trigger:
- master
- benchmarking

pool:
  vmImage: 'ubuntu-latest'

steps:

# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run benchmarks'
  
- script: |
    conda env create -n tomopy-bench -f tomopy-bench.yaml 
  displayName: 'Create benchmarking environment'

- script: |
    source activate tomopy-bench
  displayName: Activate

- script: git clone https://github.com/tomopy/tomopy-benchmarks
  displayName: 'Clone tomopy benchmarks repo'

- script: ./run-benchmarking.sh
  displayName: 'Run benchmarks'

- script: |
    cd tomopy-benchmarks
    git config --global user.name "Dreycen Foiles"
    git config --global user.email "foilesdreycen@gmail.com"
    git add *
    git commit -m "Bi-monthly benchmark"
    git push https://$(PAT)@github.com/tomopy/tomopy-benchmarks
  displayName: 'Update benchmarking data repository'
